// <auto-generated />
namespace Digoel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_PasswordStorage_Id_from_aspnetusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_PasswordStorage_Id_from_aspnetusers));
        
        string IMigrationMetadata.Id
        {
            get { return "202003211204077_remove_PasswordStorage_Id_from_aspnetusers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
