// <auto-generated />
namespace Digoel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class password_storage_id_column_added_as_a_foreign_key_in_aspnetusers_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(password_storage_id_column_added_as_a_foreign_key_in_aspnetusers_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202003210434129_password_storage_id_column_added_as_a_foreign_key_in_aspnetusers_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
