// <auto-generated />
namespace Digoel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_id_added_requird_removes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_id_added_requird_removes));
        
        string IMigrationMetadata.Id
        {
            get { return "202003211157594_user_id_added_requird_removes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
